### ISSUE TITLE
Theano Error

### ISSUE THREAD

**Issue by sahiliitm** [nyu-dl/WebNav#1]
Hi,

I tried running the code, but it gives the following error:

Using gpu device 0: Tesla K80
loading dictionary...
Loading data...
Building model
loading pre-trained weights for word embeddings
[nltk_data] Downloading package punkt to /home/iitm/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Traceback (most recent call last):
  File "run.py", line 835, in <module>
    train_lstm()
  File "run.py", line 624, in train_lstm
    grads = tensor.grad(cost, wrt=itemlist(tparams_), consider_constant=consider_constant)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 545, in grad
    grad_dict, wrt, cost_name)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1283, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1241, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 951, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1252, in access_grad_cache
    term.type.why_null)
theano.gradient.NullTypeGradError: tensor.grad encountered a NaN. This variable is Null because the grad method on the inner graph of the Scan node for{cpu,lstm_layers} returned Null for the corresponding inner input variable. The original message was: tensor.grad encountered a NaN. This variable is Null because the grad method for input 0 (TensorConstant{1}) of the ArgSortOp{quicksort, None} op is not implemented. I'm not sure if argsort should have its gradient implemented or is should be marked as undefined. So I mark it as not implemented for now.

Any idea what this may be?

Thanks!

**Comment by rodrigonogueira4** [comment]
Hello,
What version of theano are you using? It seems that this error ocurred in older versions: https://github.com/Theano/Theano/issues/3024

**Comment by sahiliitm** [comment]
Hi,
That was indeed the problem. I had installed Theano using 'pip install Theano'. After updating theano, it works. Thanks!
