### ISSUE TITLE
4files  missed in the parameter.py

### ISSUE THREAD

**Issue by SeekPoint** [nyu-dl/WebNav#4]
jeopardy_path = './data/JEOPARDY.csv'
dump_path = './data/enwiki-latest-pages-articles.xml'
path_thes_idx = "./data/th_en_US_new.idx" # Thesaurus
path_thes_dat = "./data/th_en_US_new.dat" # Thesaurus

**Comment by rodrigonogueira4** [comment]
You don't need the files to run the code:
The first two files are used to create the wikinav-jeopardy.hdf5 and wikinav-x-x.hdf5 datasets.
The last two files were used by a legacy code that performed dataset augmentation.

**Comment by SeekPoint** [comment]
sure, i am running now by delete the 4 lines
